### ISSUE TITLE
Does not function.

### ISSUE THREAD

**Issue by MagmaSlime123** [Shuzhengz/dark-discord#5]
Title.

Due to Discord switching from Babel to SWC, this breaks any and all plugins and themes.
Please update this to work with BD again.

**Comment by Shuzhengz** [comment]
This is a known issue with the new discord update and has been fixed with BD update v1.8.0 released today, please update your BD

See https://github.com/BetterDiscord/BetterDiscord/issues/1417

**Comment by MagmaSlime123** [comment]
I am updated already.

**EDIT:** Apparently reloading fixed it. Discord be weird sometimes, lol.

![image](https://user-images.githubusercontent.com/51277766/195260338-946d4fe8-0dd6-473f-bcdf-fd8f2d1ab868.png)
